### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/credit-control#220]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_credit_control - By @astirpe - #268
- [x] account_credit_control_dunning_fees - By @nguyenminhchien - #274
- [x] account_financial_risk - By @ernesto-garcia-tecnativa - #292
- [x] account_invoice_overdue_reminder - By @alexis-via - #269
- [x] account_invoice_overdue_warn - By @ValentinVinagre - #349
- [x]  account_invoice_overdue_warn_sale - By @ValentinVinagre  - #350 
- [x] account_payment_return_financial_risk - By @victoralmau - #322
- [x] partner_risk_insurance - By @victoralmau - #305
- [x] sale_financial_risk - By @stefan-tecnativa - #280
- [x] sale_financial_risk_info - By @ernesto-garcia-tecnativa - #294
- [x] sale_payment_sheet_financial_risk - By @carolinafernandez-tecnativa - #315
- [x] stock_financial_risk - By @alan196 - #299

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by alexis-via** [comment]
Migration of account_invoice_overdue_reminder https://github.com/OCA/credit-control/pull/269

**Comment by alan196** [comment]
Migration of stock_financial_risk https://github.com/OCA/credit-control/pull/299
